spring:
  application:
    name: catalog-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST_PORT:localhost:8888}
  cloud:
    config:
      profile: ${PROFILE:test}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  name: Servico de Catalogo. API REST que nos permite pesquisar o catálogo por gênero.
  author: Jardel S. Oliveira
  mail: jardeloliver197@gmail.com
  severity: Medio